import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          Try out streaming youtube video without Ads{' '}
          <Link href="api/stream" passHref>
            <code className={styles.code}>api/hello</code>
          </Link>
        </p>
      </main>
    </div>
  )
}
